version: '3'

services:
  hydra:
    image: oryd/hydra:v2.1.1
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    environment:
      - DSN=memory
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_CONSENT=http://localhost:8000/hydra/consent
      - URLS_LOGIN=http://localhost:8000/hydra/login
      - URLS_LOGOUT=http://localhost:8000/hydra/logout
    volumes:
      - ./hydra-config:/etc/config/hydra
    restart: unless-stopped

  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_PUBLIC_URL=http://localhost:4444
    depends_on:
      - hydra
    restart: unless-stopped
