[project]
name = "ory-django-auth"
version = "0.1.0"
description = "Ory Hydra Django OAuth2 Client Management"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "ory-client>=1.20.8",
]

[dependency-groups]
dev = [
    "isort>=6.0.1",
    "ruff>=0.11.6",
]
